# Generated by Django 4.1.3 on 2022-11-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0003_level_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
