# Generated by Django 4.1.3 on 2022-11-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caka.tag'),
        ),
    ]
