# Generated by Django 4.1.3 on 2022-11-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0006_what_you_learn_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Who_is_this_course_for',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caka.course')),
            ],
        ),
    ]
