# Generated by Django 4.1.3 on 2022-11-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0009_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
