# Generated by Django 4.1.3 on 2022-11-16 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0010_author_author_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Languange', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Languange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caka.languange'),
        ),
    ]
