# Generated by Django 4.1.3 on 2022-11-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0011_languange_course_languange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Languange',
            new_name='languange',
        ),
    ]
