# Generated by Django 4.1.3 on 2022-11-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0012_rename_languange_course_languange'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languange',
            new_name='Language',
        ),
    ]
