# Generated by Django 4.1.3 on 2022-11-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0013_rename_languange_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='Languange',
            new_name='language',
        ),
    ]
