# Generated by Django 4.1.3 on 2022-11-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0014_rename_languange_language_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='languange',
            new_name='language',
        ),
    ]
