# Generated by Django 4.1.3 on 2022-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0015_rename_languange_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
