# Generated by Django 4.1.3 on 2022-11-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0016_course_certificate_course_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
