# Generated by Django 4.1.3 on 2022-11-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caka', '0017_alter_course_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caka.course_type'),
        ),
    ]
